[build]
# Utilise Nixpacks (le builder recommandé par Railway)
builder = "NIXPACKS"

[deploy]
# Ton code backend est dans le dossier "backend"
rootDirectory = "backend"

# Commande de démarrage (script "start" de package.json)
startCommand = "npm start"

[deploy.env]
# Version de Node.js à utiliser (comme ton package.json -> "engines": { "node": "20.x" })
NODE_VERSION = "20"
